# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x02pb\"4\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x11\n\tcompleted\x18\x03 \x01(\x08\"&\n\x0cTaskResponse\x12\x16\n\x04task\x18\x01 \x01(\x0b\x32\x08.pb.Task\"5\n\x11\x43reateTaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tcompleted\x18\x02 \x01(\x08\x32>\n\x0bTaskService\x12/\n\nCreateTask\x12\x15.pb.CreateTaskRequest\x1a\x08.pb.Task\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASK']._serialized_start=18
  _globals['_TASK']._serialized_end=70
  _globals['_TASKRESPONSE']._serialized_start=72
  _globals['_TASKRESPONSE']._serialized_end=110
  _globals['_CREATETASKREQUEST']._serialized_start=112
  _globals['_CREATETASKREQUEST']._serialized_end=165
  _globals['_TASKSERVICE']._serialized_start=167
  _globals['_TASKSERVICE']._serialized_end=229
# @@protoc_insertion_point(module_scope)
